#!/bin/bash

#. ./host/grub/grub
# EFI_DIR
# BOOT_DIR
# BOOT_LOADER_ID

grub-install --target==${ARCH} --efi-directory=${EFI_DIR} --boot-directory=${BOOT_DIR} --bootloader-id=${BOOT_LOADER_ID}
grub-mkconfig -o ${BOOT_DIR}/grub/grub.cfg
