#!/usr/bin/bash
shell_cmd=$(basename $0)
shell_dir=$(dirname  $0)
shell_pwd=$(pwd)

SHELL_EXPAND_SUFFIX=("alisa1" "alisa2" "alisa3")

. ${shell_dir}/include/headers

case ${shell_cmd} in
        note.build)
        # note.build src=${src_dir} dis=${dis_dir_path} parent=${parent_dir_path}
        ;;
        note.publish)
        *)
        ;;
esac

