#!/usr/bin/bash
shell_cmd=$(basename $0)
shell_dir=$(dirname  $0)
shell_pwd=$(pwd)

. ${shell_dir}/include/headers


if [ ${shell_cmd} == "vulkan" ]; then
    shell_cmd="vulkan.echo"
fi

function install_base(){
    case ${gemma_pack_man} in
        gemma)
            echo "Till now,it's not ready for other package manager than pacman."
            #sudo gemma install libdrm vulkan-icd-loader vulkan-tools vulkan-headers vulkan-validation-layers vulkan-radeon nvidia-dkms shaderc
        ;;
        pacman)
            echo "Installing Basic Tools ..."
            sudo pacman -Syu libdrm vulkan-icd-loader vulkan-tools vulkan-headers vulkan-validation-layers vulkan-radeon nvidia-dkms shaderc 
        ;;
        apt)
            echo "Till now,it's not ready for other package manager than pacman."
            #sudo apt install libdrm vulkan-icd-loader vulkan-tools vulkan-headers vulkan-validation-layers vulkan-radeon nvidia-dkms shaderc
        ;;
        dnf)
            echo "Till now,it's not ready for other package manager than pacman."
            #sudo dnf install libdrm vulkan-icd-loader vulkan-tools vulkan-headers vulkan-validation-layers vulkan-radeon nvidia-dkms shaderc
        ;;
        yum)
            echo "Till now,it's not ready for other package manager than pacman."
            #sudo yum install libdrm vulkan-icd-loader vulkan-tools vulkan-headers vulkan-validation-layers vulkan-radeon nvidia-dkms shaderc
        ;;
        *)
            echo "Unknown Package Mangeer."
        ;;
    esac
}

case ${shell_cmd} in
    vulkan.prepare)
        install_base
    ;;
    vulkan.echo)
        echo "Action should be selected as vulkan.***" 
    ;;
    *)
        echo "I won't know what to do."
    ;;
esac

# switch : vulkan-mesa-layers
#    MESA_VK_DEVICE_SELECT=list vulkaninfo
#    https://wiki.archlinux.org/title/Vulkan

# slang -- shader language 
#MESA:
# wsi

#AMD

# NVIDIA : https://github.com/korvahannu/arch-nvidia-drivers-installation-guide
# pip install -r requirements.txt
# cmake -S . -B build -DUSE_VULKAN=ON
# cmake --build build
# wiki.archlinux.org/title/NVIDIA
# lspci -k -d ::03xx
# GMXXX : nvidia-dkms
#Intel :
# echo 'export VULKAN_ICD_FILENAMES=/usr/share/vulkan/icd.d/amdgpu_icd.x86_64.json' >> ~/.bashrc
# source ~/.bashrc
#cmake -S . -B build -DGGML_VULKAN=ON -D CMAKE_BUILD_TYPE=Release
#sudo pacman -S vulkan-headers

